FROM python:3.7
RUN pip3 install --upgrade pip && \
    python3 setup.py install
RUN pip3 install fastapi uvicorn

COPY ./app /app

CMD ["uvicorn","app.fastapi1:app","--host","0.0.0.0","--port","15400"]
